name: malariagen-vector-data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - scipy
  - pandas
  - dask
  - numba
  - matplotlib
  - fsspec
  - gcsfs
  - jupyterlab
  - gsutil
  - scikit-allel
  - cartopy
  - rasterio
  - bokeh
  - plotly
  - xarray
  - zarr
  - pip
  - pip:
    - jupyter-book==0.12.1
    - numpydoc==1.2.0
    - malariagen_data>=1.0.0
